### PR TITLE
Fix Issue 30 using getrandom()

### PR DESCRIPTION
**Pull request by jejb**
Replace rand() with getrandom() so the generated random sequences are unique for each run

### CODE REVIEW

**Comment by lilienbm** [comment]
Hi James,

Your getrandom generates a build warning (even if you cast to (void)) because getrandom requires you to use the result. Maybe something like this where we use getrandom and then if it doesn't work, we go back to doing byte by byte (I added srand to change the seed)

void sev::gen_random_bytes(void *bytes, size_t num_bytes)
{
    ssize_t num_gen_bytes = 0;
    num_gen_bytes = getrandom(bytes, num_bytes, 0);
    if (num_gen_bytes != (ssize_t)num_bytes) {
        printf("Warning: getrandom failed. Generating random bytes manually\n");
        // Do it manually
        uint8_t *addr = (uint8_t *)bytes;
        while (num_bytes--) {
            printf("getrandom failed\n\n");
            srand((unsigned int)time(NULL));
            *addr++ = (uint8_t)(rand() & 0xff);
        }
    }
}

**Comment by lilienbm** [comment]
Good find though! Thanks!

**Comment by jejb** [comment]
On Wed, 2021-01-06 at 21:49 +0000, Brian Lilienthal wrote:
> Hi James,
> 
> Your getrandom generates a build warning (even if you cast to (void))
> because getrandom requires you to use the result. Maybe something
> like this where we use getrandom and then if it doesn't work, we go
> back to doing byte by byte (I added srand to change the seed)
> 
> void sev::gen_random_bytes(void *bytes, size_t num_bytes)
> {
>     ssize_t num_gen_bytes = 0;
>     num_gen_bytes = getrandom(bytes, num_bytes, 0);
>     if (num_gen_bytes != (ssize_t)num_bytes) {
>         printf("Warning: getrandom failed. Generating random bytes
> manually\n");
>         // Do it manually
>         uint8_t *addr = (uint8_t *)bytes;
>         while (num_bytes--) {
>             printf("getrandom failed\n\n");
>             srand((unsigned int)time(NULL));
>             *addr++ = (uint8_t)(rand() & 0xff);
>         }
>     }
> }

Yes, that looks fine to me as a fallback, except that you probably want
srand() outside the loop because it may execute too fast and you'll get
the same seed for each call to srand().

James

**Comment by lilienbm** [comment]
Merged https://github.com/AMDESE/sev-tool/commit/eba5d419cb0b813b0b2decbb57878a9ee7cb4519

**Review by lilienbm — COMMENTED** [review]
Which format do you prefer? This file doesn't get inputted back into sev-tool, it's just for customers to compare to what the PSP reports back (not sure what format qemu/etc reports)

**Comment by jejb** [comment]
On Thu, 2021-01-07 at 08:15 -0800, Brian Lilienthal wrote:
> @lilienbm commented on this pull request.
> 
> Which format do you prefer? This file doesn't get inputted back into
> sev-tool, it's just for customers to compare to what the PSP reports
> back (not sure what format qemu/etc reports)

You mean this:

https://github.com/AMDESE/sev-tool/pull/31/commits/9ecdde4cfa07ec001406ae77f840bc2e61084a77

Sorry, that was just a stray addition this stupid github workflow makes
hard to avoid.  The reason I did the patch is that QEMU returns the
measurement as a base64 encoded binary rather than hex and getting from
hex to base64 encoded binary is somewhat annoying using shell tools. 
But I don't think it's a huge problem.

James

**Pull request closed without merging**
