### PR TITLE
Remove the use of OpenSSL internals

### PR DESCRIPTION
**Pull request by npmccallum**
This use of OpenSSL internals was gratuitous. It should now be sufficient to
build against the system OpenSSL on most Linux distributions.

### CODE REVIEW

**Comment by lilienbm** [comment]
We want a specific version of openssl because we know it doesn't have any bugs and supports all the features that we need. It's possible that someone's got a newer openssl that wouldn't work with the functions that we're calling

**Comment by lilienbm** [comment]
I still didn't get a notification when you made this request. I'm watching this and have it starred

**Comment by lilienbm** [comment]
think i fixed the notifications

**Comment by npmccallum** [comment]
@lilienbm 

1. This patch does not enable building against system OpenSSL. It merely disables the use of OpenSSL internals. Regardless of whether or not people use the system OpenSSL, you don't want or need OpenSSL internals.

2. You have no control over which OpenSSL people use unless you ship an officially supported static binary. Distributions that package this code will simply patch over your Makefile and use the system OpenSSL. Using OpenSSL internals does not defend against this.

**Comment by lilienbm** [comment]
Agreed with everything you're saying. I will test and checkin today

**Pull request merged**
