### PR TITLE
Fixes, improvements and new sign command

### PR DESCRIPTION
**Pull request by jpecholt**
Commit 1:
- Renamed Platform Owner DH to Platform DH
- Fixed package_secret: No longer SEV-hardware dependent, API obtained from PEK. Removed launch_blob dependency
- Fixed generate_launch_blob: Set as platform-independent
- Fixed some typos

Commit 2:
- New sign_pek_csr
- Updated tests.cpp: tests sign_pek_csr as well
- Updated and extended readme to include more information, sign_pek_csr
- Repurposed pek_cert_import: imports previously signed csr, does not sign it itself anymore
- New AMDCert::get_device_type(const amd_cert *ark) to obtain device type from key id in provided ark cert
- Fixed validate_cert_chain: No longer dependent on SEV hardware to obtain device type
- Improved certificate/csr check: more fields and flags checked for certs and csr
- Improved SEVCert: m_child_cert as pointer, not instance
- New SEVCert::verify_pek_csr(), removed previous variations of it in other files
- New SEVCert::verify_signed_pek_csr()
- Improved OCA cert creation: Now fields set according to API
- Improved get_ask_ark

### CODE REVIEW

**Comment by jpecholt** [comment]
Hi, I noticed that you introduced recent changes which prevent this pull request from being merged automatically. I was wondering if you are still interested in the proposed changes and additions? If so, what steps do you suggest going forward?

**Comment by lilienbm** [comment]
Hi,
Commit 1, I merged with a30a6c4cb85087f91db97c7854cd85ce7ec2a1ac and a09570792a94395ce0ffb82c9a026444aae08c20
Github said something about rebase issues and, not wanting to break your changeset, I just copied the changes over myself. 
I grabbed all your changes (hopefully) except the ones about Platform vs Platform owner naming. I'm not against changing the name, but generally we refer to the sides are Platform Owner and Guest Owner (which is separate from Guest), and thought that changing Platform Owner to Platform, might confuse the difference between Guest Owner and Guest. In SNP, the Guest has some of its own certs, so it's important to keep the distinction between Guest Owner certs and Guest certs. Please let me know your thoughts and if I missed any other changes from Commit 1. Also, sorry it took so long

**Comment by lilienbm** [comment]
I see what we're doing in Changeset 2, we're splitting up PEK_CSR into its own command and creating a separate function to verify it's created correctly. I'm just wondering what the benefit is for some of these changes? PEK_CERT_IMPORT, where most of the code currently is, and PEK_CSR both need to be run on the platform, so we're just doing this to help separate out the two steps, not specifically for any "this doesn't work on my platform" issues?

**Comment by jpecholt** [comment]
I will close this pull-request and create a new one which is based on the current master.

**Pull request closed without merging**
